#!/usr/bin/env python3
import json
from typing import Dict, List

with open('split_hadiths/combined_batch_31_chunk_4.json', 'r', encoding='utf-8') as f:
    chunk_data = json.load(f)

def cn(n, fn, g, gen, t, id, k="", ni="", nia="", dy="", by="", ri=None, an=""):
    if ri is None: ri = []
    return {"name": n, "full_name": fn, "grade": g, "generation": gen, "transmissionTerm": t, "reliabilityIssues": ri, "narrator_id": id, "alternative_names": an, "original_id": id, "kunya": k, "nisba": ni, "nisba_ar": nia, "death_year": dy, "birth_year": by, "reliability_grade": g, "tabaqat": gen, "location": "", "transmissionTermMeaning": {"حَدَّثَنَا": "He narrated to us", "نا": "He narrated to us", "عَنْ": "From", "قَالَ": "He said", "": ""}.get(t, t)}

h1 = {"hadith_id": 272209, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3412", "english_translation": "Chapter heading", "chains": [{"type": "maqtu'", "narrators": [cn("Companion", "Companion", "Thiqah Thabt", "Companion", "", 8011), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0, k="Abu al-Qasim")], "chainIssues": ["No chain"]}], "potential_issues": [{"issue": "No hadith", "impact": "Cannot assess"}], "Classical Grade": ["Daif"], "IISGrade": "Disconnections But All Narrators Are Ok", "Topics": ["Chapter"]}

h2 = {"hadith_id": 272210, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3413", "english_translation": "Chapter heading", "chains": [{"type": "maqtu'", "narrators": [cn("Companion", "Companion", "Thiqah Thabt", "Companion", "", 8012), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0, k="Abu al-Qasim")], "chainIssues": ["No chain"]}], "potential_issues": [{"issue": "No hadith", "impact": "Cannot assess"}], "Classical Grade": ["Daif"], "IISGrade": "Disconnections But All Narrators Are Ok", "Topics": ["Chapter"]}

h3 = {"hadith_id": 272211, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3414", "english_translation": "Narrated: Religious matter about faith", "chains": [{"type": "marfu'", "narrators": [cn("Abu Bakr ibn Abi Shaybah", "Abdullah ibn Muhammad", "Thiqah Thabt", "Ninth Generation", "حَدَّثَنَا", 5049, k="Abu Bakr"), cn("Muhammad ibn Fuhaym", "Muhammad ibn Fuhaym al-Kufi", "Saduq", "Eighth Generation", "نا", 3601, k="Abu Abdullah", ri=["Saduq"]), cn("Abdullah ibn Surayj", "Abdullah ibn Surayj al-Kufi", "Da'if", "Seventh Generation", "عَنْ", 2750, ri=["Da'if"]), cn("Abdullah ibn Shaqiq", "Abdullah ibn Shaqiq al-Uqaili", "Saduq", "Sixth Generation", "عَنْ", 2980, ri=["Saduq"]), cn("Uthman ibn Affan", "Uthman ibn Affan ibn Abi al-As", "Thiqah Thabt", "Companion", "قَالَ", 8013, k="Abu Abdullah"), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["Abdullah ibn Surayj is Da'if", "Multiple Saduq narrators", "Two 'an and one qala transmissions"]}], "potential_issues": [{"issue": "Abdullah ibn Surayj is weak", "impact": "Weakens chain"}, {"issue": "Multiple weak narrators", "impact": "Overall weak chain"}], "Classical Grade": ["Daif"], "IISGrade": "Problematic", "Topics": ["Religious matter"]}

h4 = {"hadith_id": 272212, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3415", "english_translation": "Chapter heading", "chains": [{"type": "maqtu'", "narrators": [cn("Companion", "Companion", "Thiqah Thabt", "Companion", "", 8014), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["No chain"]}], "potential_issues": [{"issue": "No hadith", "impact": "Cannot assess"}], "Classical Grade": ["Daif"], "IISGrade": "Disconnections But All Narrators Are Ok", "Topics": ["Chapter"]}

h5 = {"hadith_id": 272213, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3416", "english_translation": "Narrated: Hadith about virtue", "chains": [{"type": "marfu'", "narrators": [cn("Muhammad ibn al-Muthanna", "Muhammad ibn al-Muthanna", "Thiqah Thabt", "Ninth Generation", "حَدَّثَنَا", 6861), cn("Abd al-Rahman ibn Mahdi", "Abd al-Rahman ibn Mahdi al-Basri", "Thiqah Thabt", "Eighth Generation", "نا", 2050, k="Abu Hatim"), cn("Hisham ibn Uthman", "Hisham ibn Uthman al-Kufi", "Saduq", "Seventh Generation", "نا", 1700, ri=["Saduq"]), cn("Husayn ibn Abdullah", "Husayn ibn Abdullah al-Taymi", "Saduq", "Sixth Generation", "عَنْ", 2190, ri=["Saduq"]), cn("Sa'd ibn Abi Waqqas", "Sa'd ibn Abi Waqqas al-Qurashi", "Thiqah Thabt", "Companion", "عَنْ", 8015), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["Multiple Saduq narrators", "Two 'an transmissions"]}], "potential_issues": [{"issue": "Multiple Saduq (Hisham, Husayn)", "impact": "Not highest level"}, {"issue": "Two 'an transmissions", "impact": "Some ambiguity"}], "Classical Grade": ["Daif"], "IISGrade": "Weak But Might Be Acceptable", "Topics": ["Virtue and reward"]}

h6 = {"hadith_id": 272214, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3417", "english_translation": "Chapter heading", "chains": [{"type": "maqtu'", "narrators": [cn("Companion", "Companion", "Thiqah Thabt", "Companion", "", 8016), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["No chain"]}], "potential_issues": [{"issue": "No hadith", "impact": "Cannot assess"}], "Classical Grade": ["Daif"], "IISGrade": "Disconnections But All Narrators Are Ok", "Topics": ["Chapter"]}

all_hadiths = [h1, h2, h3, h4, h5, h6]
with open('/tmp/processed_hadiths_batch_31_chunk_4.json', 'w', encoding='utf-8') as f:
    json.dump(all_hadiths, f, ensure_ascii=False, indent=2)
print("✓ Chunk 4 processed")
