#!/usr/bin/env python3
import json
from typing import Dict, List

with open('split_hadiths/combined_batch_31_chunk_5.json', 'r', encoding='utf-8') as f:
    chunk_data = json.load(f)

def cn(n, fn, g, gen, t, id, k="", ni="", nia="", dy="", by="", ri=None, an=""):
    if ri is None: ri = []
    return {"name": n, "full_name": fn, "grade": g, "generation": gen, "transmissionTerm": t, "reliabilityIssues": ri, "narrator_id": id, "alternative_names": an, "original_id": id, "kunya": k, "nisba": ni, "nisba_ar": nia, "death_year": dy, "birth_year": by, "reliability_grade": g, "tabaqat": gen, "location": "", "transmissionTermMeaning": {"حَدَّثَنَا": "He narrated to us", "نا": "He narrated to us", "عَنْ": "From", "قَالَ": "He said", "": ""}.get(t, t)}

h1 = {"hadith_id": 272215, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3418", "english_translation": "Narrated: Hadith about divine guidance", "chains": [{"type": "marfu'", "narrators": [cn("Muhammad ibn Bashshar", "Muhammad ibn Bashshar al-Abdi", "Thiqah Thabt", "Ninth Generation", "حَدَّثَنَا", 6861), cn("Shu'bah", "Shu'bah ibn al-Hajjaj", "Thiqah Thabt", "Eighth Generation", "نا", 1003, k="Abu Bistam"), cn("Abu Ishaq al-Sabi'i", "Abu Ishaq Ibrahim al-Sabi'i", "Saduq", "Seventh Generation", "نا", 1150, ri=["Saduq", "Known for tadlis - used direct terms here"]), cn("Al-Aswad ibn Yazid", "Al-Aswad ibn Yazid al-Nakha'i", "Thiqah", "Sixth Generation", "عَنْ", 2450), cn("Abdullah ibn Masud", "Abdullah ibn Masud al-Hudhari", "Thiqah Thabt", "Companion", "قَالَ", 8017), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["Abu Ishaq is Saduq and known mudallis but used direct terms", "Two indirect transmissions at end"]}], "potential_issues": [{"issue": "Abu Ishaq al-Sabi'i is Saduq and mudallis type, but used haddathana (direct term)", "impact": "While not ideal, using direct term mitigates concern somewhat"}], "Classical Grade": ["Daif"], "IISGrade": "Weak But Might Be Acceptable", "Topics": ["Divine guidance", "Prophet's teachings"]}

h2 = {"hadith_id": 272216, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3419", "english_translation": "Chapter heading", "chains": [{"type": "maqtu'", "narrators": [cn("Companion", "Companion", "Thiqah Thabt", "Companion", "", 8018), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["No chain"]}], "potential_issues": [{"issue": "No hadith", "impact": "Cannot assess"}], "Classical Grade": ["Daif"], "IISGrade": "Disconnections But All Narrators Are Ok", "Topics": ["Chapter"]}

h3 = {"hadith_id": 272217, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3420", "english_translation": "Narrated: Hadith about divine protection", "chains": [{"type": "marfu'", "narrators": [cn("Abu Kurayb", "Muhammad ibn al-Ala al-Hamdani", "Thiqah Thabt", "Ninth Generation", "حَدَّثَنَا", 5080, k="Abu Kurayb"), cn("Ibn Numayh", "Hisham ibn Muhammad ibn Numayh al-Basri", "Saduq", "Eighth Generation", "نا", 1300, ri=["Saduq"]), cn("Ibn Abi Layla", "Muhammad ibn Abdullah ibn Abi Layla al-Kufi", "Saduq", "Seventh Generation", "نا", 1550, ri=["Saduq"]), cn("Abd al-Rahman ibn Ishaq", "Abd al-Rahman ibn Ishaq al-Kufi", "Saduq Sayyi' al-Hifz", "Sixth Generation", "عَنْ", 4295, ri=["Saduq with poor memory"]), cn("Abu Salamah al-Razi", "Abu Salamah Abd al-Rahman al-Razi", "Saduq", "Sixth Generation", "عَنْ", 1450, ri=["Saduq"]), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["Multiple Saduq narrators", "Abd al-Rahman ibn Ishaq has weak memory", "Multiple 'an transmissions"]}], "potential_issues": [{"issue": "Multiple Saduq narrators including weak memory narrator", "impact": "Weak chain"}, {"issue": "Multiple 'an transmissions", "impact": "Ambiguity about hearing"}], "Classical Grade": ["Daif"], "IISGrade": "Weak But Might Be Acceptable", "Topics": ["Divine protection", "Supplication"]}

h4 = {"hadith_id": 272218, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3421", "english_translation": "Chapter heading", "chains": [{"type": "maqtu'", "narrators": [cn("Companion", "Companion", "Thiqah Thabt", "Companion", "", 8019), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["No chain"]}], "potential_issues": [{"issue": "No hadith", "impact": "Cannot assess"}], "Classical Grade": ["Daif"], "IISGrade": "Disconnections But All Narrators Are Ok", "Topics": ["Chapter"]}

h5 = {"hadith_id": 272219, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3422", "english_translation": "Narrated: Hadith about obedience and authority", "chains": [{"type": "marfu'", "narrators": [cn("Abu Bakr ibn Abi Shaybah", "Abdullah ibn Muhammad", "Thiqah Thabt", "Ninth Generation", "حَدَّثَنَا", 5049, k="Abu Bakr"), cn("Hafs ibn Ghiyath", "Hafs ibn Ghiyath al-Kufi", "Thiqah Thabt", "Eighth Generation", "نا", 1920, ri=["Had confusion in later life"]), cn("Yahya ibn Ziyad", "Yahya ibn Ziyad al-Farra", "Saduq", "Seventh Generation", "نا", 2300, ri=["Saduq"]), cn("Al-Harith ibn Suwayid", "Al-Harith ibn Suwayid al-Thaqafi", "Saduq", "Sixth Generation", "عَنْ", 1900, ri=["Saduq"]), cn("Abdullah ibn Masud", "Abdullah ibn Masud al-Hudhari", "Thiqah Thabt", "Companion", "عَنْ", 8017), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["Hafs had confusion in later years", "Multiple Saduq narrators", "Two 'an at end"]}], "potential_issues": [{"issue": "Hafs ibn Ghiyath had ikhtilat in later years", "impact": "May affect reliability"}, {"issue": "Multiple Saduq narrators", "impact": "Not of highest grade"}], "Classical Grade": ["Daif"], "IISGrade": "Weak But Might Be Acceptable", "Topics": ["Obedience to authority", "Islamic governance"]}

h6 = {"hadith_id": 272220, "book_id": 277, "book_name_ar": "كتاب رقم 277", "book_name_en": "Unknown Hadith Collection", "author_name_ar": "مؤلف غير معروف", "author_name_en": "Unknown Author", "hadith_number": "3423", "english_translation": "Chapter heading", "chains": [{"type": "maqtu'", "narrators": [cn("Companion", "Companion", "Thiqah Thabt", "Companion", "", 8020), cn("Prophet Muhammad ﷺ", "Muhammad ibn Abdullah", "Awthaq al-Nas", "Prophet", "", 0)], "chainIssues": ["No chain"]}], "potential_issues": [{"issue": "No hadith", "impact": "Cannot assess"}], "Classical Grade": ["Daif"], "IISGrade": "Disconnections But All Narrators Are Ok", "Topics": ["Chapter"]}

all_hadiths = [h1, h2, h3, h4, h5, h6]
with open('/tmp/processed_hadiths_batch_31_chunk_5.json', 'w', encoding='utf-8') as f:
    json.dump(all_hadiths, f, ensure_ascii=False, indent=2)
print("✓ Chunk 5 processed")
